[devent]

# the name of the devent
name="LabWeek22"

# where the event is happening
location="Lisbon, Portugal"

# the dates the devent runs
dateStart = "2022-10-24"
dateEnd = "2022-11-4"

# a pithy tag line you want to show in the "hero/splash" part of the landing page
tagline="""
A decentralized conference hosted by Protocol Labs
"""

description="""

The Protocol Labs Network is gathering in Lisbon for our first ever decentralized conference. Teams in the network will collaborate on a variety of topics, including decentralized storage, public goods funding, cryptoeconomics, DeSci, and more.

We invite you to join us as we drive breakthroughs in computing to push humanity forward.
"""


# a link to the devent website (what domain do you expect to use?)
link="https://labweek22.on.fleek.co"

# a link to RSVP for the event
rsvpLink="https://ko59b169nlk.typeform.com/to/LHSCaePb"

# a link to the recap and videos
# Dependent on https://github.com/ipfs/ipfs-blog/issues/443 first.
# recapLink="https://blog.ipfs.io/ipfs-ping-2022-recap/"

# a link to a logo image for the event
logo="logo-hex.svg"

# a link to a large res image for the hero/splash background.
# you likely want to use the devent location/city or something meaningful to the community
bgimg="chasm.jpg"

# the organizers of the devent (usually a group)
org="Protocol Labs"

# the website of the organizers
orglink="https://protocol.ai"

# url for this event repo
repo="https://github.com/protocol/labweek-2022"

# list the participating teams.
# the format here is:
# [
#   ["Team Name", "https://team.org", "https://team.org/team-logo.jpg"],
# ]
teams = [
  ["Protocol Labs", "https://protocol.ai", "https://media.graphassets.com/e8bIG2apSUauy2dqK35W"],
  ["ConsensusLab", "https://consensuslab.world/", "./teams/consensus-lab.jpg"],
  ["Filecoin Foundation", "https://fil.org/", "./teams/filecoin-foundation.png"],
  ["Berty", "https://berty.tech", "./teams/berty.png"],
  ["ChainSafe", "https://chainsafe.io/", "./teams/chainsafe.jpeg"],
  ["Compute Over Data", "", "./teams/compute-over-data.png"],
  ["Drand", "https://drand.love", "./teams/drand.jpg"],
  ["Filswan", "https://filswan.com", "./teams/filswan.png"],
  ["Fission", "https://fission.codes", "./teams/fission.png"],
  ["IPFS", "https://ipfs.io", "./teams/ipfs.jpeg"],
  ["KEN Labs", "https://kencloud.com", "./teams/kenlabs.jpg"],
  ["LibP2P", "https://libp2p.io", "./teams/libp2p.png"],
  ["Livepeer", "https://livepeer.org", "./teams/livepeer.png"],
  ["Lotus", "https://lotus.filecoin.io", "./teams/lotus.jpeg"],
  ["Outercore", "https://ecosystem-wg.notion.site/public-Ecosystem-Working-Groups-607302c142e14ba3becdf7eb251e2b8b", "./teams/outercore.jpeg"],
  ["PL Launchpad", "https://pl-launchpad.io", "./teams/pl-launchpad.png"],
  ["Skiff", "https://skiff.com", "./teams/skiff.png"],
  ["Spaceport", "https://protocol.almanac.io/handbook/protocol-labs-spaceport-JzKymu/protocol-labs-spaceport-sFKNLxQKYdQOZfLTL4kL9uVha4TdGlYh", "./teams/spaceport.jpg"],
  ["Spice AI", "https://spice.ai", "./teams/spice-ai.jpeg"],
  ["Talent Protocol", "https://www.talentprotocol.com", "./teams/talent-protocol.png"],
]

# this is a Frequently Asked Questions section.
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[faq]

"What is the Protocol Labs Network?" = """
  Protocol Labs is an open-source research, development, and deployment laboratory. Our projects include IPFS, Filecoin, libp2p, and more. We aim to make human existence orders of magnitude better through technology.

  The Protocol Labs Network includes over 150 independent teams, working together to drive breakthroughs in computing. Our work spans the entire innovation pipeline, from the earliest research ideation to deploying end-user products. We invite like-minded teams and individuals to collaborate with us.
"""
"What is LabWeek22?" = """
  LabWeek22 is our first-ever decentralized conference. Teams in the network will spin up dozens of events over a 10-day period, including research-focused seminars, engineering workshops, summits, unconferences, and happy hours. These events will span a wide array of topics, including decentralized storage, public goods funding, cryptoeconomics, DeSci, and more.
"""
"Who is it for?" = """
  LabWeek22 brings together teams and individuals within the Protocol Labs Network, working together to collaborate on a wide array of topics and areas. Many of these events are open to all interested individuals and collaborators; please see the schedule and register to participate.
"""
"All events are optional?" = """
  Yes! This is a choose-your-own-adventure event, so please choose the events, sessions, arrival and departure dates, and activities that are interesting and relevant for you.

  A bunch of us are actively working on putting together a fantastic schedule. We want your suggestions, feedback, and additions as Pull Requests & Issues here. Please jump in to help make this thing a thing that helps you.
"""
"I’m in! How do I participate?" = """
  Great! Check out the schedule, and register for any events that you’re interested in. Each event is independently managed, and may have different policies for ticketing and registration. We invite you to join as many events as you are able to.
"""
"Can I host an event?" = """
  Yes, absolutely! Here’s what’s involved:
  
  - Identify a topic that you know a thing or two about, and think others should care more about. This can be related to IPFS/Filecoin, Web3, or innovation more generally.
  - Add your track to the schedule [here](https://labweek2022.on.fleek.co/schedule/).
  - Recruit folks you collaborate with regularly to help shape the content of your event.

  You will have total control over the structure of your event. A morning of talks and an afternoon of discussion? Go for it! Required reading before attendance? Sounds great.

  The LabWeek22 team will work with you to help situate your track in the broader schedule, give feedback, and help to make your event great. We will help you secure logistical support as needed – see [this page](https://coda.io/@stellarevents/labweek22/resources-experts-and-agencies-24) for a list of resources, or reach out to labweek22@protocol.ai for help.
"""
"How do I contact the organizers?" = """
  You can reach out to us at labweek22@protocol.ai.
"""

# this is a Resources accordian
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[resources]

"COVID-19 Policy" = """
Your safety is our priority at Lab Week! Note that there is inherent risk of exposure to COVID-19 for in-person attendees.

**Testing recommendations**
- Test before departure with a viral test (rapid antigen or PCR) as close to the time of departure as possible and no more than 3 days before travel.
- Test before each in-person attendance. If you have a positive result, please skip in-person and attend online.
- Travel with rapid antigen test kits (recommend 1-2 per day).

**Masks:** If you are not vaccinated, we strongly encourage you to wear a mask to in-person events.

**Vaccination:** If you are not up to date with your COVID-19 vaccines, we recommend that you delay travel until you are.

**Disclaimer:** This presents our recommendations, which are not binding on attendees. Please adhere to local regulations when attending Lab Week, including any requirements related to COVID-19. Each event will have their own policy and guidelines so don’t forget to check relevant event sites for any additional requirements. For more details, read our full COVID-19 Policy [here](https://coda.io/@stellarevents/labweek22/covid-19-policy-21).
"""
"Code of Conduct" = """
Please keep in mind that this is a professional event at all times, and that ALL attendees are expected to follow the [Protocol Labs Network Code of Conduct for LabWeek22](https://coda.io/@stellarevents/labweek22/code-of-conduct-13).

If you believe someone has violated this code of conduct, please reach out to abuse@protocol.ai as quickly as possible. Attendees who engage in unacceptable behavior may be removed from the event. PLN members who violate this Code of Conduct may be suspended or removed permanently from the ecosystem.
"""
"Visas" = """
We highly recommend you begin the visa process as soon as you know your travel dates. To help you out, we’ve put together a list of [required visas for entry by country of citizenship](https://coda.io/@stellarevents/labweek22/visas-23). You will also find invitation letters to support your visa application and a step by step guide to the Portugal Application Process.

If you run into issues with your visa application, please reach out to immigration@protocol.ai.
"""
"Childcare" = """
For attendees traveling with children, we’ve put together a list of [family-friendly accommodations, childcare services, and kid-friendly activities in Lisbon](https://coda.io/@stellarevents/labweek22/childcare-12). There will not be a centralized option for dropping off children during the conference, so please use the recommendations to help you plan ahead.

If you need further support, please reach out to labweek22@protocol.ai.
"""
"Exploring Lisbon" = """
To help you get ready for LabWeek22, we’ve put together [a guide to navigating Lisbon](https://coda.io/@stellarevents/labweek22/lisbon-guide-11), one of the blooming tech capitals of Europe.

You’ll find neighborhood guides, recommendations for where to eat, stay, work, and play, and even how to get around using Lisbon’s excellent array of transportation options.

Até logo!
"""

# schedule section config
[schedule]
description="""
Each event is hosted independently and ticketed separately. To register for tickets to the LabWeek22 events you'd like to attend please click on the event and visit its website. Many events are coming together, and the schedule will be updated frequently. Come back often for the latest updates.
"""

# this is a footer section, with any footer links you may want.
# there are three sections: links (general), legal (policy + terms), and social.
[footer]

[footer.links]
"Protocol Labs" = "https://protocol.ai/"
"Event Github" = "https://github.com/protocol/labweek-2022"

[footer.legal]
"Privacy Policy" = "https://protocol.ai/legal/#privacy-policy"
"Terms & Conditions" = "https://protocol.ai/legal/#terms-of-service "

[footer.social]
twitter = "ipfs"
github = "ipfs"
