# the name of your track or event
name = "ConsensusLab Summit"

# the name of the group organizing the event
org = "Consensus Lab Team"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Jorge Soares"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = ""

# the start date of the event
date = "2022-10-26"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "To be confirmed"

# the event venue name (will show up on the event card - TODO)
venueName = "Time Out Market"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Av. 24 de Julho 49, 1200-479 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""


# these is unsued:
# tickets = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = [""]

# a color, to group key events visually. use sparingly
# color=""

# a description of the event.
# will show up when the user clicks the event card.
description = """Consensus lies at the heart of blockchain networks: while enabling the decentralisation weâ€™re working towards, it also imposes scalability constraints. In the 15 months since its creation, ConsensusLab has been working on novel solutions to scaling blockchains in general and Filecoin in particular, ranging from our flagship InterPlanetary Consensus project to multi-threaded execution in FVM. Join us in Lisbon to get a sneak peek into the future of Filecoin and shape our directions, all during an afternoon of good talks, great discussions, and cold drinks.
"""
