# the name of your track or event
name = "Filecoin's Interplanetary Party"

# the name of the group organizing the event
org = "Filecoin Foundation"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Florencia Barreiro"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://fil-lisbon.io/"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "To be confirmed"

# the event venue name (will show up on the event card - TODO)
venueName = "[Suspenso](https://g.page/Suspenso_Lisboa?share)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "R. de Santiago 19, 1100-001 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Party"]

# a color, to group key events visually. use sparingly
# color=""

# the position in the schedule table, leave blank if you don't need to control this
# "top" or "bottom"
position = "top"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Kick off FIL Lisbon with the entire Filecoin community and celebrating two years since our mainnet launch, with space-y vibes!
"""
