# the name of your track or event
name = "Launchpad Social"

# the name of the group organizing the event
org = "Launchpad Team"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Hana Ahriz"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = ""

# the start date of the event
date = "2022-10-26"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "18:00 - 21:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = ""


# these is unsued:
# tickets = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = [""]

# a color, to group key events visually. use sparingly
# color=""

# a description of the event.
# will show up when the user clicks the event card.
description = """Join [ the PL Launchpad ](https://pl-launchpad.io/) Social Hour in Lisbon ! We are excited to meet all of you, share our latest updates, more about the future cohorts happening in the next months, meet the team and our current and Alumni residents.
We will be providing drinks and food for everybody in a unique location. Come enjoy a cocktail dinner and drinks and great conversations!
Protocol Labs Launchpad is a hiring & onboarding program designed for accelerating technical growth in the Web3 space.

Launchpad aims to hire exceptional talent from diverse engineering and tech operations backgrounds into a six-week, full-time residency designed to train, develop, and team-match talent with Web3 opportunities across the Protocol Labs Network.
"""
